extraction:
  cpp:
    after_prepare:
      - wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -
      - sudo apt-add-repository "deb https://apt.kitware.com/ubuntu/ `lsb_release -cs` main"
      - sudo echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list
      - wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
      - sudo apt-get update
      - sudo apt-get install -y --no-install-recommends ignition-blueprint
