version: '3.0'

services:

  # ===========
  # Base images
  # ===========

  base:
    build:
      args:
        runtime_user: root
        from: ubuntu:focal
      context: .
      dockerfile: base.Dockerfile
    image: ghcr.io/robotology/gym-ignition:base

  codespaces-base:
    build:
      args:
        runtime_user: vscode
        from: mcr.microsoft.com/vscode/devcontainers/base:focal
      context: .
      dockerfile: base.Dockerfile
    image: ghcr.io/robotology/gym-ignition:codespaces-base

  # ==============
  # Stable Channel
  # ==============

  codespaces-stable:
    depends_on: [ codespaces-base ]
    build:
      args:
        from: ghcr.io/robotology/gym-ignition:codespaces-base
        runtime_user: vscode
        ignition_codename: fortress
      context: .
      dockerfile: cicd-master.Dockerfile
    image: ghcr.io/robotology/gym-ignition:codespaces-stable

  stable: &stable
    depends_on: [ codespaces-stable ]
    build:
      args:
        from: ghcr.io/robotology/gym-ignition:codespaces-stable
        runtime_user: vscode
        gym_ignition_branch: master
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/robotology/gym-ignition:stable

  latest:
    <<: *stable
    image: ghcr.io/robotology/gym-ignition:latest

  # ===============
  # Nightly Channel
  # ===============

  codespaces-nightly:
    depends_on: [ codespaces-base ]
    build:
      args:
        from: ghcr.io/robotology/gym-ignition:codespaces-base
        runtime_user: vscode
        ignition_codename: fortress
        CMAKE_BUILD_TYPE: Debug
      context: .
      dockerfile: cicd-devel.Dockerfile
    image: ghcr.io/robotology/gym-ignition:codespaces-nightly

  nightly:
    depends_on: [ codespaces-nightly ]
    build:
      args:
        from: ghcr.io/robotology/gym-ignition:codespaces-nightly
        runtime_user: vscode
        gym_ignition_branch: devel
        pip_options: --pre
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/robotology/gym-ignition:nightly
